language: csharp

mono: none

dotnet: 2.2

solution: "./Desafio.sln"

install:
- dotnet restore

script:
- dotnet build
- dotnet test ./Desafio.Domain.Tests/Desafio.Domain.Tests.csproj
- dotnet dev-certs https
# - dotnet run  --project ./Desafio.Api/Desafio.Api.csproj
service:
- docker

# sudo: required
