CREATE TABLE [dbo].[CAD_PESSOA](
  [IDT_PESSOA] [uniqueidentifier] NOT NULL,
	[NOM_PESSOA] [varchar](255)     NOT NULL,
	[DOC_PESSOA] [varchar](14)      NOT NULL,
	[TPO_PESSOA] [int]              NOT NULL,
 CONSTRAINT [PK_CAD_PESSOA] PRIMARY KEY CLUSTERED 
(
	[IDT_PESSOA] ASC
) WITH (PAD_INDEX = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  IGNORE_DUP_KEY = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CAD_FUNDO](
	[IDT_FUNDO]       [uniqueidentifier]  NOT NULL,
	[NOM_FUNDO]       [varchar](255)      NOT NULL,
	[DOC_FUNDO]       [varchar](14)       NOT NULL,
	[VLR_INICIAL]     [decimal](18, 2)    NOT NULL,
	[DTA_REFERENCIA]  [datetime]          NOT NULL,
 CONSTRAINT [PK_CAD_FUNDO] PRIMARY KEY CLUSTERED 
(
	[IDT_FUNDO] ASC
) WITH (PAD_INDEX = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  IGNORE_DUP_KEY = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CAD_MOVIMENTACAO](
	[IDT_MOVIMENTACAO]  [uniqueidentifier]  NOT NULL,
	[TPO_MOVIMENTACAO]  [bit]               NOT NULL,
	[IDT_FUNDO]         [uniqueidentifier]  NOT NULL,
	[IDT_PESSOA]        [uniqueidentifier]  NOT NULL,
	[VLR_MOVIMENTACAO]  [decimal](18, 2)    NOT NULL,
	[DTA_MOVIMENTACAO]  [datetime]          NOT NULL,
 CONSTRAINT [PK_CAD_MOVIMENTACAO] PRIMARY KEY CLUSTERED 
(
	[IDT_MOVIMENTACAO] ASC
) WITH (PAD_INDEX = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  IGNORE_DUP_KEY = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAD_MOVIMENTACAO] WITH CHECK 
  ADD CONSTRAINT [FK_CAD_MOVIMENTACAO_CAD_FUNDO] FOREIGN KEY([IDT_FUNDO])
REFERENCES [dbo].[CAD_FUNDO] ([IDT_FUNDO])
GO

ALTER TABLE [dbo].[CAD_MOVIMENTACAO] CHECK 
  CONSTRAINT [FK_CAD_MOVIMENTACAO_CAD_FUNDO]
GO

ALTER TABLE [dbo].[CAD_MOVIMENTACAO]  WITH CHECK 
  ADD CONSTRAINT [FK_CAD_MOVIMENTACAO_CAD_PESSOA] FOREIGN KEY([IDT_PESSOA])
REFERENCES [dbo].[CAD_PESSOA] ([IDT_PESSOA])
GO

ALTER TABLE [dbo].[CAD_MOVIMENTACAO] CHECK
  CONSTRAINT [FK_CAD_MOVIMENTACAO_CAD_PESSOA]
GO
